name: dart_code_metrics
version: 5.9.0
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: '>=3.0.6 <4.0.0'

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer:
  analyzer_plugin:
  ansicolor: ^2.0.1
  args: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.0
  dart_code_metrics_presets: ^1.0.1
  file:
  glob: ^2.0.1
  html: ">=0.15.0 <1.0.0"
  http:
  meta: ^1.7.0
  path: ^1.8.0
  platform: ^3.1.0 # overridden for lowest versions compatibility
  pub_updater:
  source_span: ^1.8.0
  uuid:
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.2
  intl: ">=0.17.0 <0.19.0"
  lints:
  mocktail:
  test: ^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
